### PR TITLE
Add travis build and badge

### PR DESCRIPTION
**Pull request by keirlawson**

### CODE REVIEW

**Comment by SystemFw** [comment]
So, the problem with this is that testing is flakey at the moment. Being a rate limiter, tests are very time based, and I still haven't found a way to make this work reliably. 
Should we merge and deal with this problem later, or hold on? WDYT?

**Comment by keirlawson** [comment]
That's a fair point, best to hold on

**Comment by SystemFw** [comment]
The new cats-effect should have a test Timer. We should look into making tests reproducible with that, and then add this

**Comment by ChristopherDavenport** [comment]
@SystemFw  Can at a minimum put a compile step in so non-compiling code can't be merged.

**Comment by SystemFw** [comment]
well, sounds like it's broken :)

**Pull request merged**
